name: C++ CI Build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'output/benchmark.txt'  # Prevents workflow loop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libgsl-dev clang

    - name: Build
      run: |
        clang++ -I ./include/eigen -I /usr/include/gsl -std=c++11 Main.cpp -o bin/Mutual-BLY /usr/lib/x86_64-linux-gnu/libgsl.so /usr/lib/x86_64-linux-gnu/libgslcblas.so

    - name: Run
      run: ./bin/Mutual-BLY

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/benchmark.txt
        git commit -m "Update benchmark.txt after GitHub Actions run"
        git push
